name: Pull Request

on:
  pull_request:
    types:
      - closed

jobs:
  log-event:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Event Details
        run: |
          echo "The pull request has been closed."
          echo "Pull Request: ${{ toJson(github) }}"
